use-grammars = { only = [ "cpp", "rust", "haskell", "scheme", "python", "nix", "javascript", "html", "css"] }

[[language]]
name = "cpp"
file-types = [ "cpp", "hpp", "c", "h", "cppm", "cc" ,"hh", "zcc", "zhh" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "scheme"
language-servers = ["steel-language-server"]

[language-server.steel-language-server]
command = "steel-language-server"
args = []

[[language]]
name = "haskell"
language-servers = ["haskell-language-server"]
formatter = { command = "fourmolu" , args = ["-i"] }

[language-server.haskell-language-server]
command = "haskell-language-server-wrapper"
args = ["--lsp"]
